# specialmobs:blazes/_family_of_blazes.toml
# This config contains options that apply to the family of blazes as a whole; that is, the vanilla replacement and all
#   special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

  # Whether this mob family replaces vanilla blazes with its vanilla replacement species.
  # The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
  # <Boolean> Valid Values: { true, false }, Default: true
  general.vanilla_replacement = true

  # When greater than 0, blazes will have a random render scale applied. This is a visual effect only. If this is set
  #   to a non-negative value, it overrides the value set for "master_random_scaling", though species configs can
  #   override this value.
  # <Number> Range: -1.0 ~ 1.0, Default: -1.0
  general.family_random_scaling = -1.0

  # The chance for blazes to spawn as special variants.
  # NOTE: Some environment check types can cause deadlocks on servers currently, so be careful!
  # <Number> Range: 0.0 ~ 1.0, Default: 0.25
  general.special_variant_chance.base = 0.25
  # The chance for blazes to spawn as special variants when specific environmental conditions are met.
  # <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13
  #   world_time < 120000", "0.5 moon_phase full", "0.38 moon_phase full" ]
  #    Range for Values: 0.0 ~ 1.0
  general.special_variant_chance.exceptions = [
    "0.13 world_time < 120000",
    "0.5 moon_phase full",
    "0.38 moon_phase full"
  ]

  # The weight of each blaze species to be chosen as the replacement when blazes spawn as special variants. Higher
  #   weight is more common.
  # <Number> Range: ≥ 0.0
  general.weight.armored.base = 15.0
  general.weight.cinder.base = 0.0
  general.weight.conflagration.base = 15.0
  general.weight.ember.base = 60.0
  general.weight.hellfire.base = 60.0
  general.weight.inferno.base = 60.0
  general.weight.jolt.base = 60.0
  general.weight.wildfire.base = 60.0

  # The weight of each blaze species to be chosen as the replacement when blazes spawn as special variants when
  #   specific environmental conditions are met. Higher weight is more common.
  # <Number> Range: ≥ 0.0
  general.weight.armored.exceptions = []
  general.weight.cinder.exceptions = []
  general.weight.conflagration.exceptions = []
  general.weight.ember.exceptions = []
  general.weight.hellfire.exceptions = []
  general.weight.inferno.exceptions = []
  general.weight.jolt.exceptions = []
  general.weight.wildfire.exceptions = []
