# CREDIT MoniLabs for this workflow
name: Check ESLint in a folder
on:
  workflow_call:
    inputs:
      folder:
        required: true
        description: Path to the folder to check (e.g., 'kubejs')
        type: string

permissions:
  contents: read

jobs:
  lint-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ inputs.folder }}/package-lock.json

      - name: Install & Lint
        run: |
          cd ${{ github.workspace }}/${{ inputs.folder }}
          npm ci
          npx eslint .
        shell: bash